ERROR_CODE = {
    0000 : 'INITIAL service is normal.',
    1000 : 'initial app can not open.',
    1001 : 'Can not open menu.',
    2000 : 'Can not connect gov_24 site.',
    2010 : 'Can not create KOREA univ. ID.',
    2011 : 'Can not delete KOREA univ. ID.',
    2012 : 'Can not create KOREA univ. ID from shortcut icon.',
    2020 : 'Can not create SS_SVC repair receipt.',
    2021 : 'Can not create LG_SVC repair receipt.',
    2030 : 'Can not create University Document.',
    2040 : 'Can not connect PS&M.',
    2050 : 'Can not connect YBM 한국 TOEIC 위원회',
    3000 : 'Token 발급에 실패했습니다.',
    3001 : 'Wallet 유효성체크에 실패했습니다.',
    3002 : '개인 전자문서지갑 알림함 조회에 실패했습니다.',
    3003 : '전자증명서 발급 목록 조회에 실패했습니다.',
    3004 : '개인 전자문서지갑 팝업함 조회에 실패했습니다.',
    9999 : 'Test Result   : Fail !! (initial service is very slow.)'
}